config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "homepage#index"
  post '/import_excel', to: 'homepage#import_excel'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController 
    layout 'application'
  # GET /
  def index
    
  end

  def import_excel
    begin
      excel_importer = ExcelImporter.new
      excel_options = { file: params[:file] }
      @main_json = excel_importer.import(excel_options)
      @report = compare_json(@main_json)
    rescue Exception => exception
      @error = { msg: "Please contact admin " + exception}
    end
  end

  def compare_json(combine_summary_json)
    begin
      main_json = combine_summary_json[:main_json]
      gsp_json = combine_summary_json[:gsp_json]
      gsp_json.each_with_index do |obj, index|
        # compare entry
        main_entries = main_json[obj[0]]
        gsp_entries = obj[1]
        gsp_entries.each_with_index do |entry, i|
          if !main_entries.nil? && entry == main_entries[i]
            entry[:matched] = true
          end
        end
      end
      gsp_json
    rescue Exception => e
      @error = { msg: "Please contact admin " + exception.to_s}
    end
  end

  def compare
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homepage/import_excel.html.erb
<div class="summary">
  <div class="main-json">
    Main JSON
    <pre><%= JSON.pretty_generate(@main_json[:main_json].as_json) %></pre>
  </div>
  <div class="gsp-json">
    GSP JSON
    <pre><%= JSON.pretty_generate(@main_json[:gsp_json].as_json) %></pre>
  </div>
  <div class="report-json">
    Report
    <pre><%= JSON.pretty_generate(@report.as_json) %></pre>
  </div>
</div>

app/views/homepage/index.html.erb
<h1>Import your excel file</h1>

<%= form_tag import_excel_path, multipart: true, method: :post do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import", class: "btn btn-default" %>
    <button type="button" class="btn btn-default">OK</button>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExcelMatcher</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>